version: 2.1

executors:
  node:
    parameters:
      nodeversion:
        type: string
        default: "12"
    docker:
      - image: circleci/node:<< parameters.nodeversion >>
        environment:
          PGUSER: root
          PGDATABASE: circle_test
      - image: circleci/postgres:9-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
  github:
    docker:
      - image: cibuilds/github:0.13.0

commands:
  publish_github:
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Artifacts being published"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            ls -l ~/artifacts/*
      - run:
          name: "GHR Draft"
          command: ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ~/artifacts

jobs:
  lint:
    executor:
      name: node
      nodeversion: "12"
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint

  test:
    parameters:
      nodeversion:
        type: string
        default: "12"
      npm_install:
        type: string
        default: "ci"
    executor:
      name: node
      nodeversion: "<< parameters.nodeversion >>"
    steps:
      - checkout
      - run: npm i
      - run: npm lint
      - run: npm test

  build_artifacts:
    executor:
      name: node
      nodeversion: "12"
    steps:
      - checkout
      - run: npm ci
      - run: npm pack
      - run: cp  honeycomb-beeline-*.tgz ~/artifacts
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts
      - store_artifacts:
          path: ~/artifacts

  publish_github:
    executor: github
    steps:
      - publish_github

  publish_npm:
    executor:
      name: node
      nodeversion: "12"
    steps:
      - checkout
      - run:
          name: store npm auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm publish

# Anchor to reduce repeating filter
filters_all: &filters_all
  filters:
    tags:
      only: /.*/
filters_publish: &filters_publish
  filters:
    tags:
      only: /v[0-9].*/
    branches:
      ignore: /.*/

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - lint:
          <<: *filters_all
      - test:
          <<: *filters_all
          requires:
            - lint
          matrix:
            parameters:
              nodeversion: ["9", "10.0.0", "10", "11", "12"]
              npm_install: ["ci"] # CI only available on >=10, maybe?

  build:
    jobs:
      - lint
      - test:
          requires:
            - lint
          matrix:
            parameters:
              nodeversion: ["9", "10.0.0", "10", "11", "12"]
              npm_install: ["ci"] # CI only available on >=10, maybe?
      - build_artifacts:
          <<: *filters_publish
          requires:
            - test
      - publish_github:
          <<: *filters_publish
          context: Honeycomb Secrets
          requires:
            - build_artifacts
      - publish_npm:
          <<: *filters_publish
          context: Honeycomb Secrets
          requires:
            - test
